// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PineSms.Persistence.Services;

#nullable disable

namespace PineSms.Persistence.Migrations
{
    [DbContext(typeof(PineSmsDbContext))]
    partial class PineSmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("PineSms.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", 1)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<DateTime?>("BirthDate");

                    b.Property<int?>("BirthYear");

                    b.Property<int?>("Gender");

                    b.Property<DateTime?>("LastUsageDate");

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("SaveDate");

                    b.Property<int>("SaveType");

                    b.Property<string>("SaveUserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("PineSms.Core.Entities.SmsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", 1)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("FromNumber")
                        .IsRequired();

                    b.Property<string>("MessageText")
                        .IsRequired();

                    b.Property<string>("RecipientsJson")
                        .IsRequired();

                    b.Property<DateTime>("SendDate");

                    b.Property<string>("SendUserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SmsLog");
                });

            modelBuilder.Entity("PineSms.Core.Entities.SmsSendJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", 1)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FromNumber")
                        .IsRequired();

                    b.Property<string>("MessageText")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SmsSendJob");
                });

            modelBuilder.Entity("PineSms.Core.Entities.SmsSendJobPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", 1)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("CustomerIdsJson")
                        .IsRequired();

                    b.Property<DateTime?>("ExecutedAt");

                    b.Property<int>("JobId");

                    b.Property<int>("PartNumber");

                    b.Property<string>("ResultJson");

                    b.Property<DateTime>("ScheduledAt");

                    b.Property<int>("SentCount");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("IX_SmsSendJobPart_Status_ScheduledAt");

                    b.ToTable("SmsSendJobPart");
                });

            modelBuilder.Entity("PineSms.Core.Entities.SmsSendJobPart", b =>
                {
                    b.HasOne("PineSms.Core.Entities.SmsSendJob", "Job")
                        .WithMany("Parts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("PineSms.Core.Entities.SmsSendJob", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
