// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PineSms.Persistence.Services;

#nullable disable

namespace PineSms.Persistence.Migrations
{
    [DbContext(typeof(PineSmsDbContext))]
    partial class PineSmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PineSms.Core.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiKey_Key");

                    b.ToTable("ApiKey");
                });

            modelBuilder.Entity("PineSms.Core.Entities.BotChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaleUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFromBot")
                        .HasColumnType("bit");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaleUsername")
                        .HasDatabaseName("IX_BotChatMessage_BaleUsername");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_BotChatMessage_SentAt");

                    b.ToTable("BotChatMessage");
                });

            modelBuilder.Entity("PineSms.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsTester")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("SaveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SaveType")
                        .HasColumnType("int");

                    b.Property<string>("SaveUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("PineSms.Core.Entities.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<string>("PostalTrackingCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerOrder_OrderCode");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("CustomerOrder");
                });

            modelBuilder.Entity("PineSms.Core.Entities.MenuLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsShown")
                        .HasColumnType("bit");

                    b.Property<string>("SectionLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuLink");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IconName = "bi-house-door-fill",
                            IsShown = true,
                            SectionLabel = "منو",
                            Title = "خانه",
                            Url = "/"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IconName = "bi-person-plus-fill",
                            IsShown = true,
                            SectionLabel = "مشتریان",
                            Title = "افزودن مشتری",
                            Url = "/customer/add"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IconName = "bi-file-earmark-excel-fill",
                            IsShown = true,
                            SectionLabel = "مشتریان",
                            Title = "ورود از اکسل",
                            Url = "/customer/import"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IconName = "bi-tags-fill",
                            IsShown = true,
                            SectionLabel = "سفارشات",
                            Title = "وضعیت‌های سفارش",
                            Url = "/order/statuses"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IconName = "bi-box-seam-fill",
                            IsShown = true,
                            SectionLabel = "سفارشات",
                            Title = "بارکد پستی آناناس",
                            Url = "/order/ananas-tracking"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            IconName = "bi-key-fill",
                            IsShown = true,
                            SectionLabel = "تنظیمات",
                            Title = "کلیدهای API",
                            Url = "/settings/apikeys"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            IconName = "bi-chat-dots-fill",
                            IsShown = true,
                            SectionLabel = "ربات بله",
                            Title = "مکالمات کاربران",
                            Url = "/bot/conversations"
                        });
                });

            modelBuilder.Entity("PineSms.Core.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_OrderStatus_Code");

                    b.ToTable("OrderStatus");
                });

            modelBuilder.Entity("PineSms.Core.Entities.SmsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SendUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SmsLog");
                });

            modelBuilder.Entity("PineSms.Core.Entities.SmsSendJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SmsSendJob");
                });

            modelBuilder.Entity("PineSms.Core.Entities.SmsSendJobPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("PartNumber")
                        .HasColumnType("int");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SentCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("IX_SmsSendJobPart_Status_ScheduledAt");

                    b.ToTable("SmsSendJobPart");
                });

            modelBuilder.Entity("PineSms.Core.Entities.UserMenuLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuLinkId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MenuLinkId");

                    b.HasIndex("UserId", "MenuLinkId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserMenuLink_UserId_MenuLinkId");

                    b.ToTable("UserMenuLink");
                });

            modelBuilder.Entity("PineSms.Core.Entities.CustomerOrder", b =>
                {
                    b.HasOne("PineSms.Core.Entities.Customer", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PineSms.Core.Entities.OrderStatus", "OrderStatus")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("PineSms.Core.Entities.SmsSendJobPart", b =>
                {
                    b.HasOne("PineSms.Core.Entities.SmsSendJob", "Job")
                        .WithMany("Parts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("PineSms.Core.Entities.UserMenuLink", b =>
                {
                    b.HasOne("PineSms.Core.Entities.MenuLink", "MenuLink")
                        .WithMany("UserMenuLinks")
                        .HasForeignKey("MenuLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuLink");
                });

            modelBuilder.Entity("PineSms.Core.Entities.Customer", b =>
                {
                    b.Navigation("CustomerOrders");
                });

            modelBuilder.Entity("PineSms.Core.Entities.MenuLink", b =>
                {
                    b.Navigation("UserMenuLinks");
                });

            modelBuilder.Entity("PineSms.Core.Entities.OrderStatus", b =>
                {
                    b.Navigation("CustomerOrders");
                });

            modelBuilder.Entity("PineSms.Core.Entities.SmsSendJob", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
